name: Publish distribution ðŸ“¦ to PyPI and TestPyPI
on: [push]
jobs:
  build:
    name: Build and test Python ðŸ distributions ðŸ“¦
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    
    # Build
    - name: Install PIP dependecies
      run: >-
        python -m
        pip install
        build
        --user
    - name: Install pytest and flake dependecies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install a builded package
      run: >-
        pip install -e .
    - name: Run unit tests
      run: >-
        python -m pytest --import-mode=append tests/
  publish:
    name: Publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    # Publish
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist
    - name: Publish distribution ðŸ“¦ to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

